flink-streaming-python
tillrohrmann/flink pull request #2
Opened 2018-11-23 15:36 UTC by zentol

2018-11-23 17:27 UTC, zentol commented on flink-runtime/pom.xml
> +										<exclude>META-INF/NOTICE</exclude>
so this is quite icky, as the ASL requires us to include the NOTICE, but including it would be misleading to users.

2018-11-26 15:59 UTC, tillrohrmann requested changes
Thanks for this PR @zentol. I had some comments which we should address before merging.

2018-11-26 15:59 UTC, tillrohrmann commented on flink-libraries/flink-table/src/main/resources/META-INF/NOTICE
> +The Apache Software Foundation (http://www.apache.org/).
This file is missing the Apache dependencies:

```
- com.esri.geometry:esri-geometry-api:2.0.0
- com.google.guava:guava:19.0
- joda-time:joda-time:2.5
- net.hydromatic:aggdesigner-algorithm:6.0
- org.apache.calcite:calcite-core:1.17.0
- org.apache.calcite:calcite-linq4j:1.17.0
- org.apache.calcite.avatica:avatica-core:1.12.0
```

2018-11-26 15:59 UTC, tillrohrmann commented on flink-mesos/src/main/resources/META-INF/NOTICE
> +The Apache Software Foundation (http://www.apache.org/).
ASL 2.0 licenses:
```
- com.netflix.fenzo:fenzo-core:0.10.1
- org.apache.mesos:mesos:1.0.1
- com.fasterxml.jackson.core:jackson-annotations:2.4.0
- com.fasterxml.jackson.core:jackson-core:2.4.5
- com.fasterxml.jackson.core:jackson-databind:2.4.5
```

2018-11-26 15:59 UTC, tillrohrmann commented on flink-runtime/pom.xml
>  							<filters>
`flink-runtime` needs a NOTICE file with these ASL 2.0 dependencies:
```
- com.typesafe.akka:akka-remote_2.11:2.4.20
- io.netty:netty:3.10.6.Final
- org.apache.zookeeper:zookeeper:3.4.10
- org.uncommons.maths:uncommons-maths:1.2.2a
```

2018-11-26 15:59 UTC, tillrohrmann commented on flink-runtime/pom.xml
> +										<exclude>META-INF/NOTICE</exclude>
I think this is not so easily doable. `io.netty:netty` contains a class `Base64` which is based on `http://iharder.sourceforge.net/current/java/base64/`. Thus, the NOTICE file cannot be completely discarded. The same applies to `license/LICENSE.base64.txt`. The same applies to `LICENSE.jsr166y.txt`, `LICENSE.jzlib.txt` and `LICENSE.webbit.txt`. I guess we have to add these licenses and notices.

2018-11-26 15:59 UTC, tillrohrmann commented on flink-runtime-web/src/main/resources/META-INF/NOTICE
> +  - angular:1.3.8
my `bower.json` says `1.4.8`

2018-11-26 15:59 UTC, tillrohrmann commented on flink-runtime-web/src/main/resources/META-INF/NOTICE
> +  - font-awesome:4.5.0 (CSS)
Let's order it alphabetically

2018-11-26 15:59 UTC, tillrohrmann commented on flink-runtime-web/src/main/resources/META-INF/NOTICE
> +  - font-awesome:4.5.0 (CSS)
```
angular-ui-router#0.2.15 (MIT)
bootstrap#3.3.6 (MIT)
```
 are missing

2018-11-26 15:59 UTC, tillrohrmann commented on flink-runtime-web/src/main/resources/META-INF/NOTICE
> +The Apache Software Foundation (http://www.apache.org/).
We should also add `nvd3#1.8.4 (ASL 2.0)`

2018-11-27 13:58 UTC, zentol commented on flink-runtime/pom.xml
> +										<exclude>META-INF/NOTICE</exclude>
I've copied the listed licenses to `flink-runtime` and cut out the relevant parts of the `NOTICE` file.

2018-11-27 14:08 UTC, tillrohrmann approved these changes

2018-11-27 15:55 UTC, merged